version: '3.8'

# Services
services:

  # Nginx Service
  nginx:
    image: nginx:1.21
    container_name: iim_lemp_nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - lemp
    

  # PHP Service
  php:
    build: ./.docker/php
    working_dir: /var/www/php
    container_name: iim_lemp_php
    volumes:
      - ./src:/var/www/php
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - lemp

  # MySQL Service
  mysql:
    image: mysql/mysql-server:8.0
    hostname: iim_lemp_mysql
    container_name: iim_lemp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "localhost"
      MYSQL_DATABASE: demo
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10
    networks:
      - lemp
      
  #PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: iim_lemp_phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - lemp

# Volumes
volumes:

  mysqldata:

networks:
  lemp: